const { contextBridge, ipcRenderer } = require('electron')

contextBridge.exposeInMainWorld('directoryAPI', {
  chooseDirectory: (initialPath) => ipcRenderer.invoke('choose-directory', initialPath),
  chooseProjectIcon: (projectDirectory) => ipcRenderer.invoke('choose-project-icon', projectDirectory),
  getProjectIcon: (directory) => ipcRenderer.invoke('get-project-icon', directory),
  startWatching: (directory) => ipcRenderer.invoke('start-watching', directory),
  initializeRepository: (directory) => ipcRenderer.invoke('initialize-repository', directory),
  checkoutRepository: (directory, remote) => ipcRenderer.invoke('checkout-repository', { directory, remote }),
  stopWatching: () => ipcRenderer.invoke('stop-watching'),
  gitChanges: () => ipcRenderer.invoke('git-changes'),
  getSettings: () => ipcRenderer.invoke('get-settings'),
  getAiStatus: (provider) => ipcRenderer.invoke('get-ai-status', provider),
  loginAiProvider: (provider) => ipcRenderer.invoke('login-ai-provider', provider),
  getAppVersion: () => ipcRenderer.invoke('get-app-version'),
  getLatestRelease: () => ipcRenderer.invoke('get-latest-release'),
  openRelease: (url) => ipcRenderer.invoke('open-release', url),
  saveSettings: (settings) => ipcRenderer.invoke('save-settings', settings),
  fetchModels: (provider, endpoint) => ipcRenderer.invoke('fetch-models', { provider, endpoint }),
  getProjectAssistantContext: () => ipcRenderer.invoke('get-project-assistant-context'),
  generateProjectPlan: (instruction) => ipcRenderer.invoke('generate-project-plan', String(instruction || '')),
  applyProjectPlan: (changes) => ipcRenderer.invoke('apply-project-plan', changes),
  addGitignoreEntry: (kind, value) => ipcRenderer.invoke('add-gitignore-entry', { kind: String(kind || ''), value: String(value || '') }),
  addGitignoreSelection: (entries) => ipcRenderer.invoke('add-gitignore-selection', { entries: Array.isArray(entries) ? entries : [] }),
  generateCommitMessage: (files, operation = 'commit') => ipcRenderer.invoke('generate-commit-message', { files: Array.isArray(files) ? files.map(file => String(file)) : [], operation: String(operation || 'commit') }),
  commitPlanned: (commits) => ipcRenderer.invoke('commit-planned', commits),
  getDiff: (file) => ipcRenderer.invoke('get-diff', file),
  getStashes: () => ipcRenderer.invoke('get-stashes'),
  getHistory: (options) => ipcRenderer.invoke('get-history', options),
  getCommitFiles: (hash) => ipcRenderer.invoke('get-commit-files', hash),
  getCommitDiff: (hash, file) => ipcRenderer.invoke('get-commit-diff', { hash, file }),
  getPendingCommits: () => ipcRenderer.invoke('get-pending-commits'),
  amendCommitMessage: (message) => ipcRenderer.invoke('amend-commit-message', message),
  generateReleaseTag: () => ipcRenderer.invoke('generate-release-tag'),
  createTag: (options) => ipcRenderer.invoke('create-tag', options),
  deleteTag: (name) => ipcRenderer.invoke('delete-tag', name),
  pushTag: (name) => ipcRenderer.invoke('push-tag', name),
  stashSelected: (files, message) => ipcRenderer.invoke('stash-selected', { files, message }),
  openInExplorer: () => ipcRenderer.invoke('open-in-explorer'),
  commitSelected: (files, message, amend = false) => ipcRenderer.invoke('commit-selected', { files: Array.isArray(files) ? files.map(file => String(file)) : [], message: String(message || ''), amend: Boolean(amend) }),
  moveSelected: (files) => ipcRenderer.invoke('move-selected', { files: Array.isArray(files) ? files.map(file => String(file)) : [] }),
  refresh: () => ipcRenderer.invoke('refresh'),
  runShellCommand: (command) => ipcRenderer.invoke('run-shell-command', command),
  startTerminal: (directory) => ipcRenderer.invoke('start-terminal', directory),
  writeTerminal: (data, sessionId) => ipcRenderer.invoke('write-terminal', data, sessionId),
  resizeTerminal: (size, sessionId) => ipcRenderer.invoke('resize-terminal', size, sessionId),
  stopTerminal: (sessionId) => ipcRenderer.invoke('stop-terminal', sessionId),
  onTerminalData: (callback) => { const listener = (_, data) => callback(data); ipcRenderer.on('terminal-data', listener); return () => ipcRenderer.removeListener('terminal-data', listener) },
  onTerminalExit: (callback) => { const listener = (_, code) => callback(code); ipcRenderer.on('terminal-exit', listener); return () => ipcRenderer.removeListener('terminal-exit', listener) },
  gitPull: () => ipcRenderer.invoke('git-pull'),
  gitPush: () => ipcRenderer.invoke('git-push'),
  getBranches: () => ipcRenderer.invoke('get-branches'),
  connectRemote: (url) => ipcRenderer.invoke('connect-remote', String(url || '')),
  switchBranch: (options) => ipcRenderer.invoke('switch-branch', options),
  deleteBranch: (name) => ipcRenderer.invoke('delete-branch', String(name || '')),
  unstash: (ref) => ipcRenderer.invoke('unstash', ref),
  unstashMany: (refs) => ipcRenderer.invoke('unstash-many', refs),
  generateStashMergeMessage: (refs) => ipcRenderer.invoke('generate-stash-merge-message', refs),
  mergeStashes: (refs, message) => ipcRenderer.invoke('merge-stashes', { refs, message }),
  deleteStash: (ref) => ipcRenderer.invoke('delete-stash', ref),
  deleteStashes: (refs) => ipcRenderer.invoke('delete-stashes', refs),
  getLfsConfig: () => ipcRenderer.invoke('get-lfs-config'),
  trackLfs: (pattern) => ipcRenderer.invoke('track-lfs', pattern),
  untrackLfs: (pattern) => ipcRenderer.invoke('untrack-lfs', pattern),
  setLfsEnabled: (directory, enabled) => ipcRenderer.invoke('set-lfs-enabled', { directory, enabled }),
  unstashFiles: (ref, files) => ipcRenderer.invoke('unstash-files', { ref, files }),
  revertFiles: (files) => ipcRenderer.invoke('revert-files', files),
  getProjects: () => ipcRenderer.invoke('get-projects'),
  addProject: (project) => ipcRenderer.invoke('add-project', project),
  updateProject: (originalPath, project) => ipcRenderer.invoke('update-project', originalPath, project),
  removeProject: (directory) => ipcRenderer.invoke('remove-project', directory),
  onOpenSettings: (callback) => { ipcRenderer.on('open-settings', callback) },
  onOpenProjectAssistant: (callback) => { ipcRenderer.on('open-project-assistant', callback) },
  onOpenAbout: (callback) => { ipcRenderer.on('open-about', callback) },
  onUpdate: (callback) => { ipcRenderer.on('directory-update', (_, data) => callback(data)) }
  ,onFileIndexUpdate: (callback) => { ipcRenderer.on('file-index-update', (_, data) => callback(data)) }
  ,onOperationLog: (callback) => { ipcRenderer.on('operation-log', (_, data) => callback(data)) }
  ,onOperationProgress: (callback) => { ipcRenderer.on('operation-progress', (_, data) => callback(data)) }
  ,onAiPrompt: (callback) => { ipcRenderer.on('ai-prompt-log', (_, data) => callback(data)) }
  ,isDevelopment: process.defaultApp === true || Boolean(process.env.VITE_DEV_SERVER_URL)
  ,openDevTools: () => ipcRenderer.invoke('open-devtools')
})
