import { useEffect, useState } from 'react'
import Select from 'react-select'

const selectStyles = { container: base => ({ ...base, width: '100%' }), control: base => ({ ...base, minHeight: 38, background: '#17191c', border: '1px solid #454b51', boxShadow: 'none' }), valueContainer: base => ({ ...base, padding: '0 10px' }), menuPortal: base => ({ ...base, zIndex: 100 }), menu: base => ({ ...base, background: '#24272a', color: '#f3f4f6' }), menuList: base => ({ ...base, background: '#24272a', padding: 4 }), option: (base, state) => ({ ...base, background: state.isFocused ? '#343a3f' : '#24272a', color: '#f3f4f6', cursor: 'pointer' }), singleValue: base => ({ ...base, color: '#edf0f2' }), input: base => ({ ...base, color: '#edf0f2' }), placeholder: base => ({ ...base, color: '#89939a' }) }

export default function SettingsModal({ settings, setSettings, models, modelsLoading, loadModels, save, onClose }) {
  const modelOptions = models.map(model => ({ value: model, label: model }))
  const languageOptions = ['English', 'Italian', 'Spanish', 'French', 'German', 'Portuguese', 'Chinese', 'Japanese'].map(language => ({ value: language, label: language }))
  const reasoningOptions = [{ value: 'instant', label: 'Instant' }, { value: 'low', label: 'Low' }, { value: 'medium', label: 'Medium' }, { value: 'high', label: 'High' }]
  const [connected, setConnected] = useState(false)
  useEffect(() => { setConnected(false); if (settings.aiEnabled) void connect() }, [settings.aiEnabled, settings.endpoint])
  async function connect() { const result = await loadModels(settings.endpoint); setConnected(Array.isArray(result)) }
  return <div className="modal-backdrop settings-backdrop" onClick={onClose}><div className="settings-modal" onClick={event => event.stopPropagation()}><div className="settings-menu"><p className="eyebrow">SETTINGS</p><button className="settings-menu-item active">General</button></div><section className="settings-body"><div className="settings-head"><div><p className="eyebrow">PREFERENCES</p><h2>General</h2></div><button className="console-close-button" onClick={onClose}>×</button></div><label className="settings-toggle-row"><span><strong>Enable AI generation</strong><small>Allow Ollama to generate commit, stash and release messages.</small></span><button type="button" className={`settings-toggle ${settings.aiEnabled ? 'enabled' : ''}`} role="switch" aria-checked={settings.aiEnabled} onClick={() => setSettings({ ...settings, aiEnabled: !settings.aiEnabled })}><span /></button></label>{settings.aiEnabled && <div className="settings-ai-fields"><label>Ollama endpoint<div className="settings-endpoint-group"><input value={settings.endpoint} onChange={event => { setConnected(false); setSettings({ ...settings, endpoint: event.target.value }) }} /><button className={`ghost ${connected ? 'settings-connected' : ''}`} onClick={connect} disabled={modelsLoading || connected}>{modelsLoading ? 'Connecting…' : connected ? 'Connected' : 'Connect'}</button></div></label><label>Model<Select className="settings-select" classNamePrefix="project-select" isClearable={false} value={modelOptions.find(option => option.value === settings.model) || null} options={modelOptions} placeholder="Select a model" onChange={option => setSettings({ ...settings, model: option?.value || '' })} isLoading={modelsLoading} menuPortalTarget={document.body} styles={selectStyles} /></label><label>Message language<Select className="settings-select" classNamePrefix="project-select" isClearable={false} value={languageOptions.find(option => option.value === settings.language) || null} options={languageOptions} onChange={option => setSettings({ ...settings, language: option?.value || 'English' })} menuPortalTarget={document.body} styles={selectStyles} /></label><label>Reasoning<Select className="settings-select" classNamePrefix="project-select" isClearable={false} value={reasoningOptions.find(option => option.value === settings.reasoning) || reasoningOptions[0]} options={reasoningOptions} onChange={option => setSettings({ ...settings, reasoning: option?.value || 'instant' })} menuPortalTarget={document.body} styles={selectStyles} /></label></div>}<div className="settings-footer"><button className="ghost" onClick={onClose}>Cancel</button><button className="primary" onClick={save}>Save</button></div></section></div></div>
}
